name: Create S3 bucket
on:
  workflow_dispatch:
    inputs:
      bucketName:
        description: 'Enter S3 bucket name'
        required: true
jobs:
  create-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
            aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws-region: ap-southeast-1
      - name: Creation
        run:  |
          aws s3 mb s3://${{github.event.inputs.bucketName}}
          
          

